country_list = ['Europe & Central Asia',
                'Euro area',
                'European Union',
                'Heavily indebted poor countries (HIPC)',
                'Middle East & North Africa',
                'North America',
                'Upper middle income',
                'Sub-Saharan Africa',
                'Fragile and conflict affected situations',
                'East Asia & Pacific',
                'Central Europe and the Baltics',
                'High income',
                'Low income',
                'Low & middle income',
                'Middle income',
                'Lower middle income',
                'Least developed countries: UN classification',
                'Norway',
                'Mexico',
                'Israel',
                'Italy',
                'Japan',
                'Iraq',
                'India',
                'Haiti',
                'Greenland',
                'Iceland',
                'Hong Kong SAR, China',
                'France',
                'Denmark',
                'Cuba',
                'Croatia',
                'China',
                'Canada',
                'Afghanistan',
                'Australia',
                'United States',
                'United Arab Emirates',
                'Arab World',
                'United Kingdom',
                'Sweden',
                'Spain',
                'Saudi Arabia',
                'Russian Federation']

series_list = ['Access to electricity (% of population)',
              'Adolescent fertility rate (births per 1,000 women ages 15-19)',
              'Agricultural methane emissions (thousand metric tons of CO2 equivalent)',
              'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)',
              'Agriculture, forestry, and fishing, value added (% of GDP)',
              'Alternative and nuclear energy (% of total energy use)',
              'Arms imports (SIPRI trend indicator values)',
              'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
              'Central government debt, total (% of GDP)',
              'Chemicals (% of value added in manufacturing)',
              'Children out of school (% of primary school age)',
              'CO2 emissions (kt)',
              'CO2 emissions from manufacturing industries and construction (% of total fuel combustion)',
              'Cost of business start-up procedures (% of GNI per capita)',
              'Current health expenditure (% of GDP)',
              'Droughts, floods, extreme temperatures (% of population, average 1990-2009)',
              'Fish species, threatened',
              'Fossil fuel energy consumption (% of total)',
              'GDP (constant 2010 US$)',
              'Bribery incidence (% of firms experiencing at least one bribe payment request)',
              'Access to clean fuels and technologies for cooking (% of population)',
              'Women who believe a husband is justified in beating his wife (any of five reasons) (%)',
              'Women who believe a husband is justified in beating his wife when she refuses sex with him (%)',
              'Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)',
              'Literacy rate, adult total (% of people ages 15 and above)',
              'Marine protected areas (% of territorial waters)',
              'Mammal species, threatened',
              'Military expenditure(% of general government expenditure)',
              'Mobile cellular subscriptions (per 100 people)',
              'Multidimensional poverty headcount ratio (% of total population)',
              'Multidimensional poverty intensity (average share of deprivations experienced by the poor)',
              'Net acquisition of financial assets (% of GDP)',
              'Net official aid received (constant 2015 US$)',
              'Physicians (per 1,000 people)',
              'Plant species (higher), threatened',
              'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)',
              'Population living in slums (% of urban population)',
              'Poverty gap at $1.90 a day (2011 PPP) (%)',
              'Poverty gap at $3.20 a day (2011 PPP) (%)',
              'Poverty gap at $5.50 a day (2011 PPP) (%)',
              'Progression to secondary school (%)',
              'Primary completion rate, total (% of relevant age group)',
              'Pupil-teacher ratio, primary',
              'Pupil-teacher ratio, secondary',
              'Research and development expenditure (% of GDP)',
              'Researchers in R&D (per million people)',
              'Rural population (% of total population)',
              'Suicide mortality rate (per 100,000 population)',
              'Survival to age 65, male (% of cohort)',
              'Survival to age 65, female (% of cohort)']
